using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EWasteManagement.API.Models
{
    /// <summary>
    /// Represents an e-waste collection center entity in the database
    /// </summary>
    [Table("Centers")]
    public class Center
    {
        /// <summary>
        /// Primary key - auto-generated by database
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Name of the collection center
        /// </summary>
        [Required]
        [StringLength(200, MinimumLength = 2)]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// District where the center is located
        /// </summary>
        [Required]
        [StringLength(100)]
        public string District { get; set; } = string.Empty;

        /// <summary>
        /// Full address of the center
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Address { get; set; } = string.Empty;

        /// <summary>
        /// Contact phone number
        /// </summary>
        [Required]
        [Phone]
        [StringLength(20)]
        public string Phone { get; set; } = string.Empty;

        /// <summary>
        /// Types of e-waste items accepted (e.g., "Batteries, Electronics, Cables")
        /// </summary>
        [Required]
        [StringLength(200)]
        public string AcceptedItemType { get; set; } = string.Empty;

        /// <summary>
        /// Operating hours (e.g., "8:00 AM - 5:00 PM")
        /// </summary>
        [Required]
        [StringLength(100)]
        public string OpeningHours { get; set; } = string.Empty;

        /// <summary>
        /// Timestamp when the center was created
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Timestamp when the center was last updated
        /// </summary>
        public DateTime? UpdatedAt { get; set; }
    }
}